packages:
  - packages/*

peerDependencyRules:
  allowAny:
    - storybook

onlyBuiltDependencies:
  - '@firebase/util'
  - '@valian/eslint-config'
  - esbuild
  - nx
  - protobufjs
  - unrs-resolver

publicHoistPattern:
  - vitest-mock-extended
